spring.datasource.url=jdbc:mysql://localhost:3306/room_manager
spring.datasource.username=root
spring.datasource.password=123456

#spring.datasource.url=jdbc:mysql://103.18.6.46:3306/qmhqla07t4y1_room_manager?useSSL=false&autoReconnect=true&connectTimeout=300000&socketTimeout=300000
#spring.datasource.username=qmhqla07t4y1_cuongtd
#spring.datasource.password=cuongtd1712

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=3000
gemini.api.key=AIzaSyBW37qA1LhdQOpOxNyWBk25jXCLAnp-i6A